# Generated by Django 4.0.6 on 2022-07-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='アカウント番号')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('birthday', models.DateTimeField()),
                ('mailaddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address_pref', models.CharField(blank=True, max_length=40, verbose_name='都道府県')),
                ('address_city', models.CharField(blank=True, max_length=40, verbose_name='市区町村番地')),
                ('address_buill', models.CharField(blank=True, max_length=40, verbose_name='建物名')),
            ],
        ),
    ]
